/** Writes src/channels.generated.ts: every sense channel name in the data, as a string literal union. */
import { loadNeurons } from "../src/format.ts";
import { channelName } from "../src/senses.ts";
import { range } from "../src/util.ts";

const dataDir =
  process.argv[2] ?? new URL("../../../data", import.meta.url).pathname;
const t = await loadNeurons(`${dataDir}/neurons.json`);
const names = [
  ...new Set(
    Array.from(range(t.bodyId.length), (i) => channelName(t, i)).filter(
      (n): n is string => n !== null,
    ),
  ),
].sort();
const out = [
  "// Generated by scripts/gen-channels.ts from data/neurons.json. Do not edit.",
  "export const CHANNEL_NAMES = [",
  ...names.map((n) => `  ${JSON.stringify(n)},`),
  "] as const;",
  "export type ChannelName = (typeof CHANNEL_NAMES)[number];",
  "",
].join("\n");
await Bun.write(new URL("../src/channels.generated.ts", import.meta.url), out);
console.log(`${names.length} channel names written`);
